apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-apps
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/ykrest/helm-test.git'
    targetRevision: HEAD
    path: charts/common-apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
